person:
  name: Duyet Nguyen
  title: iOS Software Engineer
metadatas:
  - id: email
    value: duyetnt.se.uit@gmail.com
    link: mailto:duyetnt.se.uit@gmail.com
  - id: phone
    value: '+84773350530'
    link: tel:+84773350530
  - id: location
    value: Singapore
  - id: linkedin
    value: linkedin.com/in/duyetnt
    link: https://linkedin.com/in/duyetnt
summary: Passionate iOS engineer focused on building high-quality, scalable mobile products that deliver exceptional user experiences. Committed to continuous learning, mentoring, and leading teams toward technical excellence.
education:
  degree: Bachelor of Software Engineering
  school: University of Information Technology - VNU HCM
  duration: 2011 - 2016
  location: Ho Chi Minh City, Vietnam
skills:
  - iOS Development
  - Swift
  - Objective-C
  - App Architecture
  - Swift Concurrency
  - Combine
  - RxSwift
  - XCTest
  - Quick/Nimble
  - Git
  - Problem Solving
  - Teamwork
  - Communication
  - Mentoring
  - High sense of responsibility
experiences:
  - company: 
      name: OKX
      website: https://www.linkedin.com/company/okxofficial/about/
    position: Senior Software Engineer, iOS
    location: Singapore
    duration: 05/2024 - Present
    tasks:
      - Pioneered significant codebase modernisation and standardisation by spearheading the adoption of a simplified MVVM architecture variant and implementing comprehensive coding conventions, vastly enhanced readability, maintainability, and scalability across three key repositories.
      - Led revolutionary refactoring initiatives that transformed component design, reducing development time and boosting first page load time by over 200%.
      - Elevated team-wide engineering standards by introducing new architectural paradigms, significantly enhancing overall system stability, reducing critical crashes, and boosting unit test coverage.
      - Drove substantial gains in development eﬃciency by integrating AI-assisted coding, allowing the team to shift focus to critical problem-solving and innovation over repetitive tasks.
      - Mentored and guided junior engineers through complex refactoring projects, consistent code reviews, and technical consultations, ensuring successful high-quality project delivery and adherence to best practices.
  - company:
      name: TikTok
      website: https://www.linkedin.com/company/tiktok/about
    position: Software Engineer, Messaging iOS
    duration: 12/2022 - 05/2024
    location: Singapore
    tasks:
      - Implemented 6 features on time or ahead of time with good engineering practices (reusability, maintainability, unit/snapshot tests, Swift adoption, etc).
      - Took initiative to work on engineering improvement/refactoring projects, reducing code complexity/duplication and improving feature delivery eﬃciency significantly.
      - Owner of some important modules providing technical consultation/mentorship to help others design better code via tech solution/code review.
  - company:
      name: Bloomberg LP
      website: https://www.linkedin.com/company/bloomberg/about
    position: Senior Software Engineer, iOS
    duration: 02/2022 - 11/2022
    location: London, United Kingdom
    tasks:
      - Refactored oﬄine login flow and rolled out to 100% of users successfully.
      - Proposed and led the parallel UI testing initiative which cut the CI pipelines time by 30-40%.
      - Led Xcode14/iOS 16 preparation work to ensure the project compatibility and successful release upon iOS 16 oﬃcial rollout.
  - company:
      name: Delivery Hero SE
      website: https://www.linkedin.com/company/delivery-hero-se/about
    position: Software Engineer, iOS
    duration: 03/2021 - 01/2022
    location: Berlin, Germany
    tasks:
      - Delivered the native customer feedback collection feature to replace the old web view-based experience ahead of timeline.
      - Built the team's codebase from scratch with a standardised architecture (VIPER) which resulted in high maintainability and testability with ~98% unit test coverage.
      - Achieved 93% UI test coverage (the rest is untestable).
      - Was the first team implementing snapshot testing for every UI component.
  - company:
      name: Grab
      website: https://www.linkedin.com/company/grabapp/about
    position: Senior Software Engineer, iOS
    duration: 09/2018 - 11/2020
    location: Singapore
    tasks:
      - Delivered 12 features and 6 engineering improvement projects for Driver team. Most of the features were massive, complex and required a lot of communication, but I still managed to deliver way ahead of time with fully unit/UI tests covered.
      - Demonstrated good adaptability by learning a new code-base of Grab iOS app (end-user) in just a few days and delivered some important features without any issues.
      - Led the unit test modularisation project, which improved build time and dependency graph significantly.
      - Increased end to end test coverage from 0% to ~31% in 3 months.
      - Improved CI stability by investigating and fixing a lot of unstable/flaky tests which required good debugging skill and being patient.
  - company: 
      name: Misfit Wearables & Fossil Group, Inc
      website: https://www.linkedin.com/company/fossil/about
    position: Software Engineer, iOS
    duration: 09/2015 - 08/2018
    location: Ho Chi Minh City, Vietnam
    tasks:
      - Took over iOS apps development (from Fossil's former team) to interact with company's products using Bluetooth Low Energy technology (Hybrid Smartwatch) for many brands (Fossil Q, Michael Kors, Emporio Armani, Kate Spade New York...). The apps support more than 20 languages (being pulled once there is an update from the server-side).
      - Increased the scalability and reusability by separating the codebase into independent pods, sharing among 10 apps for 10 diﬀerent brands.
      - Adopted the new architecture (MVVM or later is VIPER) to make the code cleaner, more manageable and testable. VIPER is fully used in the Fossil Q app, while MVVM is fully used in the other branded apps.
